---
source: crates/ruff_linter/src/rules/flake8_async/mod.rs
---
error[ASYNC109]: 8:16: Async function definition with a `timeout` parameter

 --> ASYNC109_0.py:8:16
  |
8 | async def func(timeout):
  |                ^^^^^^^
9 |     ...
  |
  = help: Use `trio.fail_after` instead
error[ASYNC109]: 12:16: Async function definition with a `timeout` parameter

  --> ASYNC109_0.py:12:16
   |
12 | async def func(timeout=10):
   |                ^^^^^^^^^^
13 |     ...
   |
   = help: Use `trio.fail_after` instead
